- BE/backend/build.gradle
- BE/backend/src/main/resources/application.yml
* 프로젝트 필수 의존성 추가
* yml 필수 설정 추가
추후 협의 진행 이후는 H2(초기 개발단계), dev(개발이 진행된 단계), prod(배포 단계) 로 분할 할 예정입니다.
> BE 프로젝트 초기 설정(의존성 ,yml) 진행 완료

- BE/backend/src/main/java/project/main/webstore/domain/users/entity/User.java
- BE/backend/src/main/java/project/main/webstore/domain/users/enums/Grade.java
- BE/backend/src/main/java/project/main/webstore/domain/users/enums/ProviderId.java
- BE/backend/src/main/java/project/main/webstore/domain/users/enums/UserRole.java
- BE/backend/src/main/java/project/main/webstore/valueObject/Address.java
- BE/backend/src/main/java/project/main/webstore/valueObject/Duration.java
1. UserEntity 구현 및 enum 구현
2. VO 클래스 (값 타입) 구현
* VO 클래스 Address Duration 구현한 이유
1. 코드의 재활용
2. Duration 과 같은 경우는 DB 컬럼에서 startDate 와 endDate 가 있어라고 표현하는 것 보다 Duration 이 있다고 표현하면 이해하기 쉬움
3. 서로 유기적인 역할을하는 필드를 묶어서 클래스 생성 -> 이와 관련된 메서드를 해당 클래스에 만들어서 조금 더 객체지향 스러운 코드 구현
* Item 엔티티 구현 예정
엔티티별 브렌치를 나누는 이유는 하나의 브렌치에서 서로 작업을 하게 되면 git에서 충돌이 날 수 있기 때문에 브렌치를 나눠서 작업
> UserEntity 구현 및 VO클래스 구현 완료

- BE/backend/src/main/java/project/main/webstore/domain/cart/entity/Cart.java
- BE/backend/src/main/java/project/main/webstore/domain/cart/entity/CartItem.java
1. cartEntity 구현
* cartItem entity
1. cart와 item을 연결해주는 조인 테이블로 cart entity와 같은 위치에 구현하였으며, 모든 엔티티 구현이 완료되면 item과 연관 관계 구현 예정
* Order_Histroy 엔티티 구현 예정
> [feat] cartEntity 구현

- BE/backend/src/main/java/project/main/webstore/domain/coupon/entity/Coupon.java
- BE/backend/src/main/java/project/main/webstore/domain/item/entity/Item.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/entity/Notice.java
- BE/backend/src/main/java/project/main/webstore/domain/question/entity/Question.java
- BE/backend/src/main/java/project/main/webstore/domain/review/entity/Review.java
- BE/backend/src/main/java/project/main/webstore/domain/users/entity/User.java
엔티티 필드 추가 및 변경
이미지 한장만 받는 것이 아닌 List로 받게 해서 여러장의 이미지 업로드 가능하게 하기 위한 엔티티 구현
> 엔티티 필드 수정 작업 완료

- BE/backend/src/main/java/project/main/webstore/exception/BusinessLogicException.java
- BE/backend/src/main/java/project/main/webstore/exception/CommonExceptionCode.java
- BE/backend/src/main/java/project/main/webstore/exception/ErrorResponse.java
- BE/backend/src/main/java/project/main/webstore/exception/ExceptionCode.java
- BE/backend/src/main/java/project/main/webstore/exception/advice/GlobalExceptionAdvice.java
1. 예외 처리 코드 구현
- 에러 위치에 따른 예외 처리 코드 구현하기 위해 고민
- 중복적인 코드 사용을 자제하기 위해 ExceptionCode에 'HttpStatus, Message'를 사용
> [feat] 예외 처리 구현

- BE/backend/build.gradle
- BE/backend/src/main/java/project/main/webstore/config/S3Config.java
- BE/backend/src/main/java/project/main/webstore/domain/enums/Category.java
- BE/backend/src/main/java/project/main/webstore/domain/image/dto/ImageDto.java
- BE/backend/src/main/java/project/main/webstore/domain/image/entity/Image.java
- BE/backend/src/main/java/project/main/webstore/domain/image/entity/ReviewImage.java
- BE/backend/src/main/java/project/main/webstore/domain/review/dto/ReviewGetResponseDto.java
- BE/backend/src/main/java/project/main/webstore/domain/review/dto/ReviewPostRequestDto.java
- BE/backend/src/main/java/project/main/webstore/domain/review/dto/ReviewUpdateRequestDto.java
- BE/backend/src/main/java/project/main/webstore/domain/review/entity/Review.java
- BE/backend/src/main/java/project/main/webstore/domain/review/service/ReviewService.java
- BE/backend/src/main/java/project/main/webstore/utils/FileUploader.java
- BE/backend/src/main/resources/application.yml
1. S3를 이용한 이미지 저장 
2. 이미지 엔티티 구현
3. 썸네일용 리사이징 이미지 저장 구현
이미지를 저장할 때 AWS에서 자동으로 리사이징을 해서 저장하는 로직을 이용하려고 했으나 인터넷에서 과금이 될 수 있다는 것을 보고 불안해서 서버에서 리사이징 작업을 처리했다.
리사이징을 진행한 이유는 썸네일을 만들어서 간단한 조회 시 빠르게 로딩할 수 있을 것을 기대해 만들었다.
추 후 AWS서버에 리사이징 한 이미지를 저장하는 로직을 구현하고자 한다.
> 리뷰 작성 및 수정 / 삭제에 필요한 이미지 업로드 기능 구현 완료

- BE/backend/src/main/java/project/main/webstore/domain/image/dto/ImageSortDto.java
- BE/backend/src/main/java/project/main/webstore/domain/like/entity/Like.java
- BE/backend/src/main/java/project/main/webstore/domain/review/controller/ReviewController.java
- BE/backend/src/main/java/project/main/webstore/domain/review/entity/Review.java
- BE/backend/src/main/java/project/main/webstore/domain/review/mapper/ReviewMapper.java
- BE/backend/src/main/java/project/main/webstore/domain/review/repository/ReviewJpaRepository.java
- BE/backend/src/main/java/project/main/webstore/domain/review/repository/ReviewRepository.java
- BE/backend/src/main/java/project/main/webstore/domain/review/service/ReviewGetService.java
- BE/backend/src/main/java/project/main/webstore/domain/review/service/ReviewService.java
- BE/backend/src/main/resources/application.yml
리뷰 요구사항 정의서에 작성된 내용들 구현 완료
1. CRUD 작업 진행
2. Controller 구현
1. review는 특성 상 item , user 검증을 앵간한 controller 메서드에서 진행해야된다.
그렇기 때문에 이를 서비스단까지 내려가서 작업하는 것이 아닌 Controller에서 처리하는 것은 어떤지 고민이된다.
> ReviewController 1차 구현완료

- BE/backend/src/main/java/project/main/webstore/domain/image/dto/ImageInfoDto.java
- BE/backend/src/main/java/project/main/webstore/domain/image/mapper/ImageMapper.java
- BE/backend/src/main/java/project/main/webstore/domain/like/entity/Like.java
- BE/backend/src/main/java/project/main/webstore/domain/review/controller/ReviewController.java
- BE/backend/src/main/java/project/main/webstore/domain/review/entity/Review.java
- BE/backend/src/main/java/project/main/webstore/domain/review/mapper/ReviewMapper.java
- BE/backend/src/main/java/project/main/webstore/domain/review/repository/ReviewJpaRepository.java
- BE/backend/src/main/java/project/main/webstore/domain/review/service/ReviewGetService.java
- BE/backend/src/main/java/project/main/webstore/domain/review/service/ReviewService.java
1. Controller 기능 구현
2. 기능 구현 중 발생하는 오류 수정
아직 Item, User 서비스 미구현으로 인해 임시 데이터를 강제로 부여한 코드가 존재 이 부분은 추후 변경 필요
Test코드 미작성
시큐리티 적용 이후 테스트 코드 추가 작성 할 예정
> reviewController 구현 완료

- BE/backend/src/main/java/project/main/webstore/domain/image/entity/NoticeImage.java
- BE/backend/src/main/java/project/main/webstore/domain/image/utils/ImageUtils.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/entity/Notice.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/exception/NoticeException.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/repository/NoticeJpaRepository.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/repository/NoticeRepository.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/service/NoticeGetService.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/service/NoticeService.java
- BE/backend/src/main/java/project/main/webstore/domain/review/repository/ReviewRepository.java
- BE/backend/src/test/java/project/main/webstore/domain/review/service/ReviewServiceTest.java
1. 이미지 관련 로직 클래스로 빼서 모듈화
2. 공지사항 조회 클래스 구현
3. 공지사항 수정 삭제 등록 클래스 구현
이미지 관련 로직을 리뷰에서 구현하면서 따로 모듈화 했으면 좋겠다는 생각을 했었고 와일드 카드를 이용해서 메서드를 전부 수정 및 모듈화를 진행했다.
> noticeService 구현 완료

- BE/backend/src/main/java/project/main/webstore/domain/image/entity/NoticeImage.java
- BE/backend/src/main/java/project/main/webstore/domain/image/utils/ImageUtils.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/controller/NoticeController.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/dto/NoticeGetResponseDto.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/dto/NoticeGetSimpleResponseDto.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/dto/NoticeIdResponseDto.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/dto/NoticePatchRequestDto.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/dto/NoticePostRequestDto.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/entity/Notice.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/exception/NoticeException.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/mapper/NoticeMapper.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/repository/NoticeJpaRepository.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/repository/NoticeRepository.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/service/NoticeGetService.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/service/NoticeService.java
- BE/backend/src/main/java/project/main/webstore/domain/review/repository/ReviewRepository.java
- BE/backend/src/main/java/project/main/webstore/utils/UriCreator.java
- BE/backend/src/test/java/project/main/webstore/domain/review/service/ReviewServiceTest.java
1. 이미지 처리 관련 메서드 모듈화
2. CRUD 작업
이미지 처리를 모듈화 할 때 와일드 카드를 사용해 처리 진행 -> 이미지 저장할때 사용할 엔티티들을 Image 클래스를 상속해서 만든 코드의 강점을 알 수 있었다.
많지 않은 데이터만를 여러개 보내야할 때 정보를 최적화 해서 보내야하는가 아니면 조금 더 많은 데이터를 같이 보내야하는가 고민
이전 PR들(feat/BE/notice 로의 PR)을 보면 자세하게 적혀있습니다.
> notice 1차 구현 완료

- BE/backend/src/main/java/project/main/webstore/domain/qna/dto/AnswerDto.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/dto/QuestionDto.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/entity/Answer.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/entity/Question.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/enums/QnaStatus.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/exception/QnaExceptionCode.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/repository/AnswerRepository.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/repository/QuestionRepository.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/service/QnaGetService.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/service/QnaService.java
1. 서비스 로직 구현 완료
답변만을 조회하는 경우가 없다 -> 조회를 담당하는 서비스에서는 QuestionRepository만을 이용해서 기능 구현 완료
> 서비스로직 구현 완료

- BE/backend/src/main/java/project/main/webstore/domain/item/entity/Item.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/controller/QnaController.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/dto/AnswerDto.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/dto/AnswerPostRequestDto.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/dto/QuestionPatchDto.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/dto/QuestionPostRequestDto.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/entity/Answer.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/entity/Question.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/mapper/QnaMapper.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/service/QnaGetService.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/service/QnaService.java
1. 컨트롤러 구현 작업
2. 작업에 필요한 연관관계 추가 매핑
작업 진행 시 어떻게 조회를 하는 것이 조금 더 효율적인지 생각하면서 작업을 진행했다.
> 게시판 컨트롤러 구현 완료

- BE/backend/Dockerfile.yml
- BE/backend/build.gradle
- BE/backend/src/main/java/project/main/webstore/config/SwaggerConfig.java
1. 도커 파일 설정
2. 스웨거 Config 설정
트리거 테스트를 위한 PR
> 도커 및 스웨거 설정 1차 완료 및 트리거 테스트를 위한 PR

- FE/src/App.tsx
- FE/src/Components/KYH/Mypage/MainContainer.tsx
- FE/src/Components/KYH/admin/AdminNav.tsx
- FE/src/Components/KYH/admin/HomeNavigate.tsx
- FE/src/Components/KYH/admin/MenuNav.tsx
- FE/src/Components/KYH/admin/ProductInquiry/ResultTable.tsx
- FE/src/Components/KYH/admin/ProductInquiry/SearchTable.tsx
- FE/src/Components/KYH/admin/ProductList/ProductList.tsx
- FE/src/Components/KYH/admin/ProductList/Table.tsx
- FE/src/Components/KYH/admin/ProductList/TableContents.tsx
- FE/src/Components/KYH/admin/ProductList/TableTitle.tsx
- FE/src/Components/KYH/admin/ReturnOrExchange/ResultTable.tsx
- FE/src/Components/KYH/admin/ReturnOrExchange/SearchTable.tsx
- FE/src/Pages/KYH/Admin.tsx
- FE/src/Pages/KYH/Mypage.tsx
- FE/tailwind.config.js
- 라우팅 방식 수정(Outlet 활용)
- 관리자 페이지 디자인 수정
> 라우팅 방식 수정 및 관리자 페이지 디자인 수정

- FE/src/Components/LSM/Notice/NoticeList/ContentsItem.tsx
- FE/src/Components/LSM/Notice/NoticeList/ContentsList.tsx
- FE/src/Pages/LSM/Notice/NoticeList.tsx
- FE/tailwind.config.js
- 공지사항 메인페이지 박스 정렬 UI 일부 수정
- 공지사항 메인페이지 contentsList 코드 일부 수정
- css 커스텀 추가
- 없음
> 공지사항 메인 페이지 UI 및 코드 일부 수정

- BE/backend/src/main/java/project/main/webstore/config/RedisConfig.java
- BE/backend/src/main/java/project/main/webstore/config/SecurityConfig.java
- BE/backend/src/main/java/project/main/webstore/config/javaConfig.java
- BE/backend/src/main/java/project/main/webstore/domain/users/controller/UserController.java
- BE/backend/src/main/java/project/main/webstore/domain/users/dto/UserPostRequestDto.java
- BE/backend/src/main/java/project/main/webstore/domain/users/entity/User.java
- BE/backend/src/main/java/project/main/webstore/domain/users/enums/UserRole.java
- BE/backend/src/main/java/project/main/webstore/domain/users/service/UserService.java
- BE/backend/src/main/java/project/main/webstore/domain/users/service/UserValidService.java
- BE/backend/src/main/java/project/main/webstore/exception/CommonExceptionCode.java
- BE/backend/src/main/java/project/main/webstore/redis/RedisUtils.java
- BE/backend/src/main/java/project/main/webstore/security/AuthController.java
- BE/backend/src/main/java/project/main/webstore/security/dto/LoginDto.java
- BE/backend/src/main/java/project/main/webstore/security/dto/LoginResponseDto.java
- BE/backend/src/main/java/project/main/webstore/security/dto/UserInfoDto.java
- BE/backend/src/main/java/project/main/webstore/security/jwt/entryPoint/UserAuthEntryPoint.java
- BE/backend/src/main/java/project/main/webstore/security/jwt/filter/JwtAuthenticationFilter.java
- BE/backend/src/main/java/project/main/webstore/security/jwt/filter/JwtVerificationFilter.java
- BE/backend/src/main/java/project/main/webstore/security/jwt/handler/FailAuthenticationHandler.java
- BE/backend/src/main/java/project/main/webstore/security/jwt/handler/SuccessAuthenticationHandler.java
- BE/backend/src/main/java/project/main/webstore/security/jwt/handler/SuccessSimpleUrlHandler.java
- BE/backend/src/main/java/project/main/webstore/security/jwt/utils/JwtTokenizer.java
- BE/backend/src/main/java/project/main/webstore/security/jwt/utils/TransMessageUtils.java
- BE/backend/src/main/java/project/main/webstore/security/jwt/utils/UserDetailsServiceAuth.java
- BE/backend/src/main/resources/application.yml
1. JWT를 통한 시큐리티 구현
1. 로그인 URL 변경을 통한 URL 통일
2. 시큐리티 필터의 중요성 (필터를 통한 인증, 인가 작업이 진행된다.)
3. 인가 실패 시 entryPoint를 통해 예외 옵션 별 작업 응답 데이터 분기(서명 오류 or 시간 만료)
생각보다 시큐리티는 필터가 많이 중요하고 Config 에서의 설정이 중요하다.
UserController 구현을 통한 User 도메인 완성, OAuth 2의 경우는 Controller 구현 이후 작업 예정
> JWT토큰을 토한 작업 구현

- FE/src/App.tsx
- FE/src/Pages/KHJ/Header/Header.tsx
- FE/src/Pages/LSM/BasicLayout.tsx
- FE/src/Pages/LSM/Footer.tsx
변경사항
- Header, Footer 연결 및 라우팅
> Header, Footer 연결 및 라우팅

- FE/src/Components/KHJ/Nav/GlobalNav.tsx
- FE/src/Components/KHJ/Nav/NavBottom.tsx
> [fix] console 에러 수정

- BE/backend/build.gradle
- BE/backend/src/main/java/project/main/webstore/config/SwaggerConfig.java
- BE/backend/src/main/java/project/main/webstore/domain/image/dto/ImageDto.java
- BE/backend/src/main/java/project/main/webstore/domain/image/dto/ImageSortDto.java
- BE/backend/src/main/java/project/main/webstore/domain/image/mapper/ImageMapper.java
- BE/backend/src/main/java/project/main/webstore/domain/item/controller/ItemController.java
- BE/backend/src/main/java/project/main/webstore/domain/item/controller/OptionController.java
- BE/backend/src/main/java/project/main/webstore/domain/item/controller/SpecController.java
- BE/backend/src/main/java/project/main/webstore/domain/item/dto/ItemIdResponseDto.java
- BE/backend/src/main/java/project/main/webstore/domain/item/dto/ItemPatchDto.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/controller/QnaController.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/dto/AnswerDto.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/dto/AnswerPostRequestDto.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/dto/QuestionDto.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/dto/QuestionPatchDto.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/dto/QuestionPostRequestDto.java
- BE/backend/src/main/java/project/main/webstore/domain/review/controller/ReviewController.java
- BE/backend/src/main/java/project/main/webstore/domain/review/dto/ReviewGetResponseDto.java
- BE/backend/src/main/java/project/main/webstore/domain/review/dto/ReviewIdResponseDto.java
- BE/backend/src/main/java/project/main/webstore/domain/review/dto/ReviewPostRequestDto.java
- BE/backend/src/main/java/project/main/webstore/domain/review/dto/ReviewUpdateRequestDto.java
- BE/backend/src/main/java/project/main/webstore/domain/review/mapper/ReviewMapper.java
- BE/backend/src/main/java/project/main/webstore/domain/review/service/ReviewGetService.java
- BE/backend/src/main/java/project/main/webstore/domain/review/service/ReviewService.java
- BE/backend/src/main/java/project/main/webstore/domain/users/controller/UserController.java
- BE/backend/src/main/java/project/main/webstore/domain/users/dto/UserPostRequestDto.java
- BE/backend/src/main/java/project/main/webstore/dto/ResponseDto.java
- BE/backend/src/main/resources/application.yml
- BE/backend/src/test/java/project/main/webstore/domain/review/service/ReviewGetServiceTest.java
- BE/backend/src/test/java/project/main/webstore/domain/review/service/ReviewServiceTest.java
> 스웨거 임시 구현 완료

- BE/backend/src/main/java/project/main/webstore/config/SwaggerConfig.java
- BE/backend/src/main/java/project/main/webstore/domain/image/dto/ImageSortDto.java
- BE/backend/src/main/java/project/main/webstore/domain/review/dto/ReviewPostRequestDto.java
> 스웨거 설정 오류 수정

- BE/backend/src/main/java/project/main/webstore/domain/users/service/UserService.java
- BE/backend/src/main/java/project/main/webstore/enums/ResponseCode.java
- BE/backend/src/main/java/project/main/webstore/security/AuthController.java
- BE/backend/src/main/java/project/main/webstore/security/dto/LoginDto.java
* 스웨거 로그인 구현 실패로 인한 임시 로그인 컨트롤러 구현
* 추 후 시큐리티의 학습을 통해 미구현된 로그인 기능을 스웨거에 추가할 예정
> 스웨거 임시 로그인 구현 완료

- BE/backend/src/main/java/project/main/webstore/config/WebConfig.java
- BE/backend/src/main/java/project/main/webstore/domain/item/service/ItemService.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/service/NoticeService.java
- BE/backend/src/main/java/project/main/webstore/domain/review/controller/ReviewController.java
- BE/backend/src/main/java/project/main/webstore/domain/review/dto/ReviewPostRequestDto.java
- BE/backend/src/main/java/project/main/webstore/domain/review/service/ReviewService.java
- BE/backend/src/main/java/project/main/webstore/security/AuthController.java
- BE/backend/src/main/java/project/main/webstore/security/dto/LoginDto.java
> 스웨거 설정을 위한 로직 수정

- BE/backend/src/test/java/project/main/webstore/domain/review/service/ReviewServiceTest.java
* 배포를 위한 테스트 임시 주석처리
* 이미치 처리방식 모듈화를 통한 구조 변경 테스트 미반영
* 배포 진행 이후 바로 테스트 코드 구현 예정
> 배포를 위한 테스트 임시 주석처리

- FE/package.json
- FE/src/App.tsx
- package.json script 코드 일부 수정
- App.tsx 내 라우터 path 오류 수정
> script 코드 및 라우터 path 오류 수정

- BE/backend/src/main/java/project/main/webstore/domain/item/entity/Item.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/entity/Notice.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/controller/QnaController.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/dto/AnswerDto.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/dto/AnswerPostRequestDto.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/dto/QuestionDto.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/dto/QuestionPatchDto.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/dto/QuestionPostRequestDto.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/entity/Answer.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/entity/Question.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/mapper/QnaMapper.java
- BE/backend/src/main/java/project/main/webstore/domain/users/controller/UserController.java
- BE/backend/src/main/java/project/main/webstore/domain/users/dto/UserPostRequestDto.java
- BE/backend/src/main/java/project/main/webstore/domain/users/entity/User.java
- BE/backend/src/main/java/project/main/webstore/domain/users/exception/UserExceptionCode.java
- BE/backend/src/main/java/project/main/webstore/domain/users/repository/UserRepository.java
- BE/backend/src/main/java/project/main/webstore/domain/users/service/UserService.java
- BE/backend/src/main/java/project/main/webstore/email/event/UserRegistrationApplicationEvent.java
- BE/backend/src/main/java/project/main/webstore/email/event/UserRegistrationEventListener.java
- BE/backend/src/main/resources/templates/email-registration-member.html
1. url 수정 (중복된 url)
2. 질의응답 비밀글 삭제
3. user도메인 닉네임 체크 로직 추가
4. 회원 가입 시 이메일 인증 추가
* 회의를 통한 로직 수정으로 인한 서비스 변경
* 메일 인증 시 성공 모달창에 대한 문제가 존재
> 로직 1차 수정 와료

- BE/backend/src/main/java/project/main/webstore/config/SecurityConfig.java
- BE/backend/src/main/java/project/main/webstore/domain/cart/entity/Cart.java
- BE/backend/src/main/java/project/main/webstore/domain/image/utils/ImageUtils.java
- BE/backend/src/main/java/project/main/webstore/domain/item/entity/Item.java
- BE/backend/src/main/java/project/main/webstore/domain/item/mapper/ItemMapper.java
- BE/backend/src/main/java/project/main/webstore/domain/users/entity/User.java
- BE/backend/src/main/java/project/main/webstore/domain/users/mapper/UserMapper.java
- BE/backend/src/test/java/project/main/webstore/domain/image/utils/ImageUtilsTest.java
- BE/backend/src/test/java/project/main/webstore/domain/item/service/ItemServiceTest.java
- BE/backend/src/test/java/project/main/webstore/domain/item/stub/ItemStub.java
- BE/backend/src/test/java/project/main/webstore/domain/review/service/ReviewServiceTest.java
- BE/backend/src/test/java/project/main/webstore/domain/users/service/UserServiceTest.java
- BE/backend/src/test/java/project/main/webstore/domain/users/stub/UserStub.java
- BE/backend/src/test/java/project/main/webstore/stub/ImageStub.java
> 코스 에러 설정추가

- FE/src/utils/auth/submitUserData.js
> useNavigate 오류 수정

- FE/src/Components/KYH/SignIn/EmailAndPWContainer.tsx
- FE/src/Components/KYH/SignUp/EmailContainer.tsx
- FE/src/Components/KYH/SignUp/NicknameContainer.tsx
- FE/src/Components/KYH/SignUp/PasswordConfirmContainer.tsx
- FE/src/Components/KYH/SignUp/PasswordContainer.tsx
- FE/src/Components/KYH/SignUp/PhoneContainer.tsx
- FE/src/Components/KYH/SignUp/UserNameContainer.tsx
> import 구문 린트 오류 수정

- BE/backend/src/main/java/project/main/webstore/domain/coupon/entity/Coupon.java
- BE/backend/src/main/java/project/main/webstore/domain/image/entity/NoticeImage.java
- BE/backend/src/main/java/project/main/webstore/domain/image/entity/ReviewImage.java
- BE/backend/src/main/java/project/main/webstore/domain/image/utils/ImageUtils.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/controller/NoticeController.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/dto/NoticeGetResponseDto.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/dto/NoticeGetSimpleResponseDto.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/dto/NoticePatchRequestDto.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/entity/Notice.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/service/NoticeService.java
- BE/backend/src/main/java/project/main/webstore/domain/order/mapper/OrderMapper.java
- BE/backend/src/main/java/project/main/webstore/domain/review/controller/ReviewController.java
- BE/backend/src/main/java/project/main/webstore/domain/review/dto/ReviewGetResponseDto.java
- BE/backend/src/main/java/project/main/webstore/domain/review/dto/ReviewPostRequestDto.java
- BE/backend/src/main/java/project/main/webstore/domain/review/entity/Review.java
- BE/backend/src/main/java/project/main/webstore/domain/review/repository/ReviewJpaRepository.java
- BE/backend/src/main/java/project/main/webstore/domain/review/service/ReviewService.java
- BE/backend/src/main/java/project/main/webstore/domain/users/dto/UserGetResponseDto.java
- BE/backend/src/main/java/project/main/webstore/domain/users/dto/UserPatchRequestDto.java
- BE/backend/src/main/java/project/main/webstore/domain/users/dto/UserPostRequestDto.java
- BE/backend/src/main/java/project/main/webstore/domain/users/entity/User.java
- BE/backend/src/main/java/project/main/webstore/domain/users/service/UserService.java
- BE/backend/src/test/java/project/main/webstore/domain/review/service/ReviewServiceTest.java
- BE/backend/src/test/java/project/main/webstore/domain/review/stub/ReviewStub.java
- BE/backend/src/test/java/project/main/webstore/domain/users/stub/UserStub.java
- BE/backend/src/test/java/project/main/webstore/stub/ImageStub.java
* S3과금 이슈로 인한 이미지 로직 수정
* 요구사항 변경으로 인한 불필요한 필드 제거
> 요구사항 수정으로 인한 수정사항 적용

- BE/backend/src/main/java/project/main/webstore/domain/config/WebConfigFilter.java
- BE/backend/src/main/java/project/main/webstore/domain/log/filter/LogUrlMethodFilter.java
- log MethodFilter 생성
- filter ConfigFilter 생성
> [feat]feat/BE/logging

- BE/backend/src/main/java/project/main/webstore/config/SwaggerConfig.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/controller/NoticeController.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/dto/NoticeGetResponseDto.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/dto/NoticeGetSimpleResponseDto.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/entity/Notice.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/enums/NoticeCategory.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/mapper/NoticeMapper.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/service/NoticeGetService.java
- BE/backend/src/main/java/project/main/webstore/domain/orderHistory/entity/OrderHistory.java
- BE/backend/src/main/java/project/main/webstore/domain/review/controller/ReviewController.java
- BE/backend/src/main/java/project/main/webstore/domain/review/dto/ReviewGetResponseDto.java
- BE/backend/src/main/java/project/main/webstore/domain/review/dto/ReviewPostRequestDto.java
- BE/backend/src/main/java/project/main/webstore/domain/review/dto/ReviewUpdateRequestDto.java
- BE/backend/src/main/java/project/main/webstore/security/AuthController.java
- BE/backend/src/main/java/project/main/webstore/utils/FileUploader.java
- BE/backend/src/main/resources/application.yml
- BE/backend/src/test/java/project/main/webstore/domain/review/stub/ReviewStub.java
1. 스웨거 작업자 그룹별 구현할 API 분류
* 추가 구현 API 발견으로 인한 1차 완성
> Swagger 그룹 분리 1차 완성

- BE/backend/src/main/java/project/main/webstore/domain/users/controller/UserController.java
- BE/backend/src/main/java/project/main/webstore/domain/users/dto/UserGetPasswordRequestDto.java
- BE/backend/src/main/java/project/main/webstore/domain/users/dto/UserGetPasswordResponseDto.java
- BE/backend/src/main/java/project/main/webstore/domain/users/entity/User.java
- BE/backend/src/main/java/project/main/webstore/domain/users/mapper/UserMapper.java
- BE/backend/src/main/java/project/main/webstore/domain/users/repository/UserRepository.java
- BE/backend/src/main/java/project/main/webstore/domain/users/service/UserService.java
- BE/backend/src/main/java/project/main/webstore/email/enums/CheckCondition.java
- BE/backend/src/main/java/project/main/webstore/email/event/UserRegistrationApplicationEvent.java
- BE/backend/src/main/java/project/main/webstore/email/event/UserRegistrationEventListener.java
- BE/backend/src/main/java/project/main/webstore/security/AuthController.java
- BE/backend/src/main/resources/application.yml
1. password 변경
* 회원 이름, 비밀번호, 메일 확인 후 변경 로직
* 추후 본인 인증 로직 수정 예정
2. 휴면계정 상태 변경
* 이벤트 발급을 통해 사용자의 상태 변경
> userAPI 추가 구현

- FE/package-lock.json
- FE/package.json
- FE/src/Components/KHJ/Nav/NavBottom.tsx
- FE/src/Components/KHJ/Nav/NavTop.tsx
- FE/src/Components/KYH/Mypage/MainContainer.tsx
- FE/src/Components/KYH/Mypage/ProfileContainer.tsx
- FE/src/Components/KYH/Mypage/UserInfo/NicknameContainer.tsx
- FE/src/Components/KYH/Mypage/UserInfo/UserInfo.tsx
- FE/src/Components/KYH/SignIn/OneClickLogInContainer.tsx
- FE/src/Components/KYH/SignIn/SignInForm.tsx
- FE/src/Components/KYH/SignUp/NicknameContainer.tsx
- FE/src/Components/KYH/SignUp/SignUpForm.tsx
- FE/src/Components/KYH/admin/ProductList/ProductList.tsx
- FE/src/Components/KYH/admin/Sales/Chart.tsx
- FE/src/Components/KYH/admin/Sales/Sales.tsx
- FE/src/Components/KYH/admin/Sales/SalesChart.tsx
- FE/src/Components/KYH/admin/Sales/SalesChartHeader.tsx
- FE/src/Components/KYH/admin/Sales/TableContents.tsx
- FE/src/Components/KYH/admin/Sales/TableTitle.tsx
- FE/src/Pages/KYH/Mypage.tsx
- FE/src/hooks/mypage/useFetchProfile.tsx
- FE/src/index.tsx
- FE/src/utils/auth/authValidate.ts
- FE/src/utils/auth/fetchLogOut.ts
- FE/src/utils/auth/fetchSignIn.ts
- FE/src/utils/auth/signUpRegEx.js
- FE/tailwind.config.js
- 로그아웃 기능 구현
- 사용자 프로필 조회
- 닉네임 밸리데이션 추가
- 로그인, 회원가입 디자인 수정
> 로그아웃 기능 구현, 사용자 프로필 조회 커스텀 훅 구현

- BE/backend/src/main/java/project/main/webstore/config/OauthConfig.java
- BE/backend/src/main/java/project/main/webstore/config/SecurityConfig.java
- BE/backend/src/main/java/project/main/webstore/config/SwaggerConfig.java
- BE/backend/src/main/java/project/main/webstore/config/javaConfig.java
- BE/backend/src/main/java/project/main/webstore/domain/users/controller/UserController.java
- BE/backend/src/main/java/project/main/webstore/domain/users/enums/ProviderId.java
- BE/backend/src/main/java/project/main/webstore/domain/users/repository/UserRepository.java
- BE/backend/src/main/java/project/main/webstore/domain/users/service/UserService.java
- BE/backend/src/main/java/project/main/webstore/exception/CommonExceptionCode.java
- BE/backend/src/main/java/project/main/webstore/security/oauth2/handler/OAuth2UserSuccessHandler.java
- BE/backend/src/main/resources/application.yml
> 구글 OAuth2 설정 완료

- FE/src/App.tsx
- FE/src/Components/LSM/Notice/NoticeList/ContentsItem.tsx
- FE/src/Components/LSM/Notice/NoticeList/ContentsList.tsx
- FE/src/Components/LSM/Notice/NoticeList/TabList.tsx
- FE/src/Components/LSM/Notice/NoticeList/TabListItem.tsx
- FE/src/Pages/LSM/Notice/NoticeList.tsx
- 공지사항 메인(리스트) 페이지 데이터 get 요청
- 각 요소를 상세 페이지에 동적라우팅 적용
- 카테고리별 탭 메뉴 필터 적용
> 공지사항 메인(리스트) 페이지 기능 구현

- BE/backend/src/main/java/project/main/webstore/domain/item/dto/ItemPatchDto.java
- BE/backend/src/main/java/project/main/webstore/domain/item/dto/ItemPostDto.java
- BE/backend/src/main/java/project/main/webstore/domain/item/entity/Item.java
- BE/backend/src/main/java/project/main/webstore/domain/item/service/ItemService.java
- BE/backend/src/main/java/project/main/webstore/domain/users/dto/UserOrderDto.java
- BE/backend/src/main/java/project/main/webstore/domain/users/entity/User.java
- BE/backend/src/main/java/project/main/webstore/security/oauth2/handler/OAuth2UserSuccessHandler.java
1. 마일리지 제거
* User , Item 엔티티 마일리지 제거 및 이에따른 DTO, Service 코드 수정
> 마일리지 제거 완료

- FE/src/Components/LSM/Notice/NoticeList/ContentsItem.tsx
- FE/src/Components/LSM/Notice/NoticeList/ContentsList.tsx
- FE/src/Pages/LSM/Notice/NoticeList.tsx
- 전체 카테고리 get 요청 api 수정 및 데이터 size 수정
- 요소 타이틀 글자 수 제한 및 image가 null일 때 UI 수정
> 공지사항 메인(리스트) 페이지 수정

- BE/backend/src/main/java/project/main/webstore/domain/item/dto/OptionPostRequestDto.java
- BE/backend/src/main/java/project/main/webstore/domain/item/dto/OptionResponseDto.java
- BE/backend/src/main/java/project/main/webstore/domain/item/dto/SpecPostDto.java
- BE/backend/src/main/java/project/main/webstore/domain/item/dto/SpecResponseDto.java
- BE/backend/src/main/java/project/main/webstore/domain/item/entity/ItemOption.java
- BE/backend/src/main/java/project/main/webstore/domain/item/mapper/OptionMapper.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/controller/NoticeController.java
- BE/backend/src/test/java/project/main/webstore/domain/users/stub/UserStub.java
- BE/backend/src/test/java/project/main/webstore/totalTest/ItemControllerTest.java
- BE/backend/src/test/java/project/main/webstore/totalTest/QnaControllerTest.java
> qna 구현 완료

- FE/src/Components/KYH/admin/MenuNav.tsx
- FE/src/Components/LSM/Notice/NoticeDetail/Contents.tsx
- FE/src/Components/LSM/Notice/NoticeDetail/Date.tsx
- FE/src/Components/LSM/Notice/NoticeDetail/IconButton.tsx
- FE/src/Components/LSM/Notice/NoticeDetail/ImageBox.tsx
- FE/src/Components/LSM/Notice/NoticeDetail/TabTitle.tsx
- FE/src/Components/LSM/Notice/NoticeDetail/Title.tsx
- FE/src/Components/LSM/Notice/NoticeForm/Button.tsx
- FE/src/Components/LSM/Notice/NoticeForm/NoticeForm.tsx
- FE/src/Components/LSM/Notice/NoticeForm/Select.tsx
- FE/src/Components/LSM/Notice/NoticeForm/Textarea.tsx
- FE/src/Components/LSM/Notice/NoticeForm/TitleInput.tsx
- FE/src/Components/LSM/Notice/NoticeList/IconButton.tsx
- FE/src/Components/LSM/Notice/NoticeTitle.tsx
- FE/src/Components/LSM/Product/ProductForm/ImageInput.tsx
- FE/src/Pages/LSM/Notice/NoticeDetail.tsx
- FE/src/Pages/LSM/Notice/NoticeEdit.tsx
- FE/src/Pages/LSM/Notice/NoticeList.tsx
- FE/src/Pages/LSM/Notice/NoticePost.tsx
- admin 페이지 공지사항 라우팅 수정
- admin 페이지 공지사항 등록 버튼 추가
- admin 페이지 공지사항 수정 레이아웃 수정
- admin 페이지 공지사항 등록 레이아웃 수정
- 공지사항 상세 페이지 get 요청 및 데이터 연결
- 공지사항 등록 페이지 post 요청
- 공지사항 상세 페이지 delete 요청
> 공지사항 상세/등록/수정 페이지 수정

- FE/src/Components/LSM/Notice/NoticeForm/NoticeForm.tsx
- FE/src/Components/LSM/Notice/NoticeForm/Select.tsx
> 공지사항 등록 페이지 수정

- FE/src/Components/LSM/Notice/NoticeForm/Button.tsx
- FE/src/Components/LSM/Notice/NoticeForm/ImageInput.tsx
- FE/src/Components/LSM/Notice/NoticeForm/NoticeForm.tsx
- FE/src/Components/LSM/Notice/NoticeForm/Select.tsx
- FE/src/Components/LSM/Notice/NoticeForm/TitleInput.tsx
- FE/src/Pages/LSM/Notice/NoticeEdit.tsx
- FE/src/Pages/LSM/Notice/NoticePost.tsx
- 공지사항 등록 페이지 데이터 get 요청 분기처리
- 공지사항 수정 페이지 데이터 get 요청
- 공지사항 등록 시 글자 수 제한(40자) 구현
- 메뉴 바 위로 컨텐츠가 올라오는 UI 수정
- 공지사항 수정 버튼 onClick 핸들러 분기처리
- 공지사항 등록 시 이미지 post 요청 및 미리보기, UI 수정
- 공지사항 form 이미지 post 요청 구현, patch 요청 구현 진행중
> 공지사항 등록 페이지 수정, 수정 페이지 일부 수정

- BE/backend/src/main/java/project/main/webstore/domain/cart/dto/CartDeleteDto.java
- BE/backend/src/main/java/project/main/webstore/domain/cart/dto/CartPatchRequestDto.java
- BE/backend/src/main/java/project/main/webstore/domain/cart/enums/CartExceptionCode.java
- BE/backend/src/main/java/project/main/webstore/domain/cart/mapper/CartMapper.java
- BE/backend/src/main/java/project/main/webstore/domain/cart/service/CartService.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/controller/NoticeController.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/entity/Notice.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/mapper/NoticeMapper.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/controller/QnaController.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/dto/AnswerDto.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/dto/AnswerPostRequestDto.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/dto/QuestionDto.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/dto/QuestionIdResponseDto.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/dto/QuestionPatchDto.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/mapper/QnaMapper.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/service/QnaService.java
- BE/backend/src/main/java/project/main/webstore/domain/users/controller/UserController.java
- BE/backend/src/main/java/project/main/webstore/domain/users/dto/ShippingInfoPostDto.java
- BE/backend/src/main/java/project/main/webstore/domain/users/dto/UserGetResponseDto.java
- BE/backend/src/main/java/project/main/webstore/domain/users/dto/UserPatchRequestDto.java
- BE/backend/src/main/java/project/main/webstore/domain/users/entity/User.java
- BE/backend/src/main/java/project/main/webstore/domain/users/mapper/UserMapper.java
- BE/backend/src/main/java/project/main/webstore/domain/users/service/UserService.java
- BE/backend/src/test/java/project/main/webstore/helper/TestUtils.java
- BE/backend/src/test/java/project/main/webstore/totalTest/CartControllerTest.java
- BE/backend/src/test/java/project/main/webstore/totalTest/QnaControllerTest.java
> QnA Test코드 1차완성

- FE/src/App.tsx
- FE/src/Components/LSM/Notice/NoticeDetail/IconButton.tsx
- FE/src/Components/LSM/Notice/NoticeDetail/ImageBox.tsx
- FE/src/Components/LSM/Notice/NoticeDetail/TabTitle.tsx
- FE/src/Components/LSM/Notice/NoticeForm/Button.tsx
- FE/src/Components/LSM/Notice/NoticeForm/ImageInput.tsx
- FE/src/Components/LSM/Notice/NoticeForm/NoticeForm.tsx
- FE/src/Components/LSM/Notice/NoticeForm/Select.tsx
- FE/src/Components/LSM/Notice/NoticeForm/Textarea.tsx
- FE/src/Components/LSM/Notice/NoticeForm/TitleInput.tsx
- FE/src/Components/LSM/Notice/NoticeTitle.tsx
- FE/src/Pages/LSM/Notice/NoticeDetail.tsx
- FE/src/Pages/LSM/Notice/NoticeEdit.tsx
- FE/src/Pages/LSM/Notice/NoticePost.tsx
- 공지사항 수정 페이지 동적 라우팅
- 수정 페이지일 경우 기능 구현, post와 edit 분기 설정
> 공지사항 수정 페이지 수정

- BE/backend/src/main/java/project/main/webstore/domain/notice/entity/Notice.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/mapper/NoticeMapper.java
- BE/backend/src/main/java/project/main/webstore/domain/order/entity/Orders.java
- BE/backend/src/main/java/project/main/webstore/domain/order/enums/OrderedItem.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/controller/QnaController.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/dto/QuestionPostRequestDto.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/entity/Answer.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/entity/Question.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/mapper/QnaMapper.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/service/QnaGetService.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/service/QnaService.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/service/QnaValidService.java
- BE/backend/src/main/java/project/main/webstore/domain/users/service/UserValidService.java
- BE/backend/src/main/java/project/main/webstore/utils/UriCreator.java
- BE/backend/src/test/java/project/main/webstore/annotation/WithMockCustomUser.java
- BE/backend/src/test/java/project/main/webstore/annotation/WithMockCustomUserSecurityContextFactory.java
- BE/backend/src/test/java/project/main/webstore/domain/order/stub/OrderStub.java
- BE/backend/src/test/java/project/main/webstore/domain/qna/controller/QnaControllerTest.java
- BE/backend/src/test/java/project/main/webstore/domain/qna/service/QnaServiceTest.java
- BE/backend/src/test/java/project/main/webstore/domain/qna/service/QnaValidServiceTest.java
- BE/backend/src/test/java/project/main/webstore/domain/qna/stub/QnaStub.java
- BE/backend/src/test/java/project/main/webstore/helper/TestUtils.java
- BE/backend/src/test/java/project/main/webstore/totalTest/NoticeControllerTest.java
- BE/backend/src/test/java/project/main/webstore/totalTest/QnaControllerTest.java
1. Service 코드 분리
* validService. getService, Service로 분리
2. testCode 구현
* 통합 테스트 구현
* 단위 테스트 구현 (컨트롤러, 서비스 계층)
> QnA 구현 및 리펙토링 완료

- FE/.eslintrc.json
- FE/babel.config.js
- FE/jest.config.js
- FE/package-lock.json
- FE/package.json
- FE/src/Components/KYH/Mypage/UserInfo/UserInfo.tsx
- FE/src/Components/KYH/admin/ProductList/Option.tsx
- FE/src/Components/KYH/admin/ProductList/OptionTitle.tsx
- FE/src/Components/KYH/admin/ProductList/OrderListBtnContainer.tsx
- FE/src/Components/KYH/admin/ProductList/ProductDetail.tsx
- FE/src/Components/KYH/admin/ProductList/ProductDetailContents.tsx
- FE/src/Components/KYH/admin/ProductList/ProductDetailTitle.tsx
- FE/src/Components/KYH/admin/ProductList/ProductList.tsx
- FE/src/Components/KYH/admin/ProductList/Table.tsx
- FE/src/Components/KYH/admin/ProductList/TableContents.tsx
- FE/src/hooks/admin/product/useFetchProductDetail.ts
- FE/tailwind.config.js
- FE/tsconfig.json
- 판매상품 리스트 상세페이지 UI 및 데이터 조회 기능 구현
- 판매상품 삭제기능(다중 선택) 구현
- 개인정보 수정, 주소 수정 이벤트 및 로직 분리
- 상품 상제 정보 조회 custom hook 구현
> 판매상품 페이지 기능 구현 및 개인정보 기능 수정

- FE/src/Components/LSM/Notice/NoticeDetail/IconButton.tsx
- FE/src/Components/LSM/Notice/NoticeDetail/TabTitle.tsx
- FE/src/Components/LSM/Notice/NoticeForm/NoticeForm.tsx
- FE/src/Pages/LSM/Notice/NoticeDetail.tsx
- 뒤로가기 버튼 클릭 시 navigate 경로 재설정
- category 필드 patch 요청 시 버그 서버 수정 확인 후 console.log 코드 삭제
> 공지사항 상세 페이지 수정

- BE/backend/src/main/java/project/main/webstore/domain/image/utils/ImageUtils.java
- BE/backend/src/main/java/project/main/webstore/domain/item/exception/ItemExceptionCode.java
- BE/backend/src/main/java/project/main/webstore/domain/item/service/ItemService.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/service/QnaService.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/service/QnaValidService.java
- BE/backend/src/main/java/project/main/webstore/domain/review/controller/ReviewController.java
- BE/backend/src/main/java/project/main/webstore/domain/review/dto/ReviewBestRequestDto.java
- BE/backend/src/main/java/project/main/webstore/domain/review/dto/ReviewBestResponseDto.java
- BE/backend/src/main/java/project/main/webstore/domain/review/dto/ReviewGetResponseDto.java
- BE/backend/src/main/java/project/main/webstore/domain/review/dto/ReviewLikeResponseDto.java
- BE/backend/src/main/java/project/main/webstore/domain/review/dto/ReviewPostRequestDto.java
- BE/backend/src/main/java/project/main/webstore/domain/review/dto/ReviewUpdateRequestDto.java
- BE/backend/src/main/java/project/main/webstore/domain/review/entity/Review.java
- BE/backend/src/main/java/project/main/webstore/domain/review/mapper/ReviewMapper.java
- BE/backend/src/main/java/project/main/webstore/domain/review/service/ReviewService.java
- BE/backend/src/main/java/project/main/webstore/domain/users/service/UserValidService.java
- BE/backend/src/main/java/project/main/webstore/security/AuthController.java
- BE/backend/src/test/java/project/main/webstore/domain/qna/service/QnaServiceTest.java
- BE/backend/src/test/java/project/main/webstore/domain/qna/service/QnaValidServiceTest.java
- BE/backend/src/test/java/project/main/webstore/domain/review/controller/ReviewControllerTest.java
- BE/backend/src/test/java/project/main/webstore/domain/review/service/ReviewServiceTest.java
- BE/backend/src/test/java/project/main/webstore/domain/review/stub/ReviewStub.java
- BE/backend/src/test/java/project/main/webstore/helper/TestUtils.java
- BE/backend/src/test/java/project/main/webstore/stub/ImageStub.java
- BE/backend/src/test/java/project/main/webstore/totalTest/ReviewControllerTest.java
1. ValidService, GetService, Service 분리
* 검증을 위한 Service 코드 분리로 인해 다른 도메인에서 검증 위한 의존성 추가 시 불필요한 의존성 추가 막을 수 있음
2. Test 코드 작성
* 단위 테스트 ,통합테스트 구현
* 통합 테스트 구현 시 TestRestTemplate 구현했으나 MockMvc만으로도 가능하다고 판단 MockMvc 진행
* TestRestTemplate의 경우 추 후 시나리오 테스트 구현  시 사용 예정
* 두 방법의 차이는 서블릿 컨테이너 생성 유무의 차이와 그로인한 롤백 여부의 차이
> Review 리펙토링 및 Test 구현

- BE/backend/src/test/java/project/main/webstore/domain/review/controller/ReviewControllerTest.java
메서드 구조 변경으로 인한 Test Mocking 변경
> Review Test 수정본 추가

- FE/.github/workflows/deploy.yml
> [chore] 빌드 및 배포 yaml 파일 작성

- FE/.github/workflows/deploy.yml
> [chore] deploy.yml 파일 수정

- FE/.github/workflows/deploy.yml
> [chore] deploy.yml 수정

- FE/src/Pages/LSM/Main.tsx
> [test] 배포자동화 테스트

- FE/.github/workflows/deploy.yml
- deploy.yml 파일 내 s3 연결 코드 일부 수정
> [chore] deploy.yml 파일 내 s3 연결 코드 일부 수정

- FE/src/Pages/LSM/Main.tsx
> [test] test 코드 수정

- FE/public/index.html
- https 프로토콜 에러 관련 수정
- react-quill link 태그 추가
> [fix] https 프로토콜 에러 관련 수정 및 react-quill link 태그 추가

- .github/workflows/deploy.yml
> [chore] github actions 워크플로우 생성

- .github/workflows/deploy.yml
> [chore] build 관련 코드 수정

- .github/workflows/deploy.yaml
> [chore] deploy.yaml 빌드 코드 일부 수정

- .github/workflows/deploy.yaml
> [chore] deploy.yaml 코드 일부 수정

- .github/workflows/deploy.yaml
> [chore] css 파일 build 코드 추가

- FE/package.json
> [chore] pakage.json 스크립트 코드 수정

- .github/workflows/deploy.yaml
- FE/package.json
> [chore] css 빌드 파일 관련 수정

- FE/src/Pages/LSM/Main.tsx
> [test] 배포자동화 테스트 코드 작성

- FE/package.json
- FE/public/index.html
- FE/tailwind.config.js
> [chore] tailwind css 빌드 관련 코드 수정

- FE/src/Pages/LSM/Notice/NoticeList.tsx
> [fix] 타입에러 코드 수정

- .github/workflows/deploy.yaml
- cloudfront deploy 관련 파일 코드 제거 및 수정
> [chore] cloudfront deploy 관련 파일 코드 제거 및 수정

- FE/src/App.tsx
> [fix] build 시 에러 발생, 중복 코드 수정

- FE/public/index.html
> [fix] API https 리디렉션 코드 삭제

- .github/workflows/deploy.yaml
> [chore] api 도메인 환경변수 설정 코드 추가

- FE/src/Components/LSM/Main/BestProduct/BestItem.tsx
- FE/src/Components/LSM/Main/BestProduct/BestItemInfo.tsx
- FE/src/Components/LSM/Main/BestProduct/BestItemList.tsx
- FE/src/Components/LSM/Main/BestProduct/Button.tsx
- FE/src/Components/LSM/Main/BestProduct/TagList.tsx
- FE/src/Components/LSM/Main/BestReview/ReviewItem.tsx
- FE/src/Components/LSM/Main/BestReview/ReviewItemList.tsx
- FE/src/Components/LSM/Main/MainBestProduct.tsx
- FE/src/Components/LSM/Main/MainBestReview.tsx
- FE/src/Components/LSM/Main/MainNewProduct.tsx
- FE/src/Components/LSM/Main/MainThemeProduct.tsx
- FE/src/Components/LSM/Main/MainTitle.tsx
- FE/src/Components/LSM/Main/NewProduct/NewItem.tsx
- FE/src/Components/LSM/Main/NewProduct/NewItemInfo.tsx
- FE/src/Components/LSM/Main/NewProduct/NewItemList.tsx
- FE/src/Components/LSM/Main/ThemeProduct/Button.tsx
- FE/src/Components/LSM/Main/ThemeProduct/ThemeItem.tsx
- FE/src/Components/LSM/Main/ThemeProduct/ThemeItemList.tsx
- FE/src/Components/LSM/Notice/NoticeForm/Select.tsx
- FE/src/Pages/LSM/Main.tsx
- 메인 페이지 best-item 데이터 api 연결 및 UI 수정
- 메인 페이지 new-item 데이터 api 연결 및 UI 수정
- 메인 페이지 best-review 데이터 api 연결 및 UI 수정
- 메인 페이지 theme 데이터 api 연결 및 UI 수정
- 메인 페이지 event UI 삭제
- 메인 페이지 UI 일부 수정
- 공지사항 상세 페이지 console.log 코드 삭제
> 메인(랜딩) 페이지 작업 및 UI 수정, console.log 코드 제거

- FE/src/Components/LSM/Main/BestProduct/BestItem.tsx
- FE/src/Components/LSM/Main/BestProduct/BestItemList.tsx
- FE/src/Components/LSM/Main/NewProduct/NewItem.tsx
- FE/src/Components/LSM/Main/NewProduct/NewItemList.tsx
- FE/src/Pages/LSM/Main.tsx
- FE/src/Pages/LSM/Notice/NoticeList.tsx
- 메인페이지 해상도 넓을 경우 왼쪽으로 쏠리는 UI 수정
- 메인페이지 캐러셀 화살표 버튼 사라짐 현상 수정
- 공지사항 리스트 관리자 페이지 왼쪽 마진 제거
> [design] UI 수정

- FE/src/Components/KYH/admin/ProductList/Table.tsx
> [feat] ItemId 관련 redux 설정

- FE/src/Components/CYW/ProductDetail/Tab/ProductTab/ProductTab.tsx
> [feat] 업로드 내용으로 상품 상세 표현

- FE/package-lock.json
- FE/public/tailwind.css
- FE/src/Components/LSM/Product/ProductForm/Button.tsx
- FE/src/Components/LSM/Product/ProductForm/CategoryInput.tsx
- FE/src/Components/LSM/Product/ProductForm/CheckBox.tsx
- FE/src/Components/LSM/Product/ProductForm/ContentsInput.tsx
- FE/src/Components/LSM/Product/ProductForm/ImageInput.tsx
- FE/src/Components/LSM/Product/ProductForm/OptionInput.tsx
- FE/src/Components/LSM/Product/ProductForm/OrderInput.tsx
- FE/src/Components/LSM/Product/ProductForm/PriceInput.tsx
- FE/src/Components/LSM/Product/ProductForm/ProductForm.tsx
- FE/src/Components/LSM/Product/ProductForm/Select.tsx
- FE/src/Components/LSM/Product/ProductForm/TitleInput.tsx
- FE/src/Pages/LSM/Notice/NoticeList.tsx
- FE/src/index.css
- 공지사항 리스트 페이지 수 조정
- 상품 등록/수정 버튼 분기 설정
- 상품명 인풋 구현
- 금액 인풋 구현
- 카테고리 인풋 구현
- 배송비 인풋 구현
- 옵션 인풋 구현
- 이미지 인풋 구현
- react-quill 에디터 구현
- 상품 등록 데이터 post 요청을 통해 서버와 연결
> 상품 등록 페이지(관리자) 기능 구현 및 공지사항 페이지 수정

- FE/src/api/index.js
- axios interceptors관련 무한요청 수정
> axios interceptors관련 무한요청 수정

- BE/backend/src/main/java/project/main/webstore/domain/cart/controller/CartController.java
- BE/backend/src/main/java/project/main/webstore/domain/cart/dto/CartGetResponseDto.java
- BE/backend/src/main/java/project/main/webstore/domain/cart/dto/CartPatchRequestDto.java
- BE/backend/src/main/java/project/main/webstore/domain/cart/entity/CartItem.java
- BE/backend/src/main/java/project/main/webstore/domain/cart/mapper/CartMapper.java
- BE/backend/src/main/java/project/main/webstore/domain/cart/service/CartService.java
- BE/backend/src/main/java/project/main/webstore/domain/item/controller/ItemController.java
- BE/backend/src/main/java/project/main/webstore/domain/item/entity/ItemOption.java
- BE/backend/src/main/java/project/main/webstore/domain/item/service/ItemService.java
- BE/backend/src/main/java/project/main/webstore/domain/order/dto/OrderLocalDto.java
- BE/backend/src/main/java/project/main/webstore/domain/order/dto/OrderPostDto.java
- BE/backend/src/main/java/project/main/webstore/domain/order/entity/Orders.java
- BE/backend/src/main/java/project/main/webstore/domain/order/service/OrderService.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/controller/QnaController.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/enums/QnaStatus.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/repository/QuestionRepository.java
- BE/backend/src/main/java/project/main/webstore/domain/qna/service/QnaGetService.java
- BE/backend/src/test/java/project/main/webstore/domain/qna/controller/QnaControllerTest.java
1. QnA 관리자 페이지 조회 시 조건별 조회로 변경
2. 상품 수정 시 로직 변경
3. 장바구니 로직 수정
- 장바구니 수정 통합 (삭제 / 수량 변경 )
4. 주문 로직 수정
- 장바구니 특정 상품만 주문 하도록 수정
> Item Order 도메인 수정

- FE/src/Components/CYW/OrderedList/ResultTableTitle.tsx
- FE/src/Components/KYH/admin/AdminMain/InquiryList.tsx
- FE/src/Components/KYH/admin/AdminMain/InquiryListTitle.tsx
- FE/src/Components/KYH/admin/AdminMain/OrderList.tsx
- FE/src/Components/KYH/admin/AdminMain/OrderListTable.tsx
- FE/src/Components/KYH/admin/AdminMain/OrderListTableContents.tsx
- FE/src/Components/KYH/admin/AdminMain/OrderListTableTitle.tsx
- FE/src/Components/KYH/admin/AdminMain/OrderListTitle.tsx
- FE/src/Components/KYH/admin/ProductInquiry/ProductInquiry.tsx
- FE/src/Components/KYH/admin/ProductInquiry/SearchTable.tsx
- FE/src/Components/KYH/admin/ProductInquiry/SearchTableContents.tsx
- FE/src/Components/KYH/admin/ProductList/CloseBtn.tsx
- FE/src/Components/KYH/admin/ProductList/OptionContents.tsx
- FE/src/Components/KYH/admin/ProductList/ProductDetail.tsx
- FE/src/Components/KYH/admin/ProductList/ProductDetailContents.tsx
- FE/src/hooks/admin/inquiry/useFetchInquiry.ts
- FE/src/hooks/admin/inquiry/useFetchInquiryPaging.ts
- FE/src/hooks/admin/product/useFetchProducts.ts
- FE/src/utils/productDetail/fetchReview.ts
- 관리자 메인페이지 더보기 기능 추가
- 관리자 주문된 상품내역, 판매상품 리스트 디자인 수정
> 관리자 메인 페이지 더보기 기능 추가 및 디자인 수정

- FE/src/Components/KYH/SignUp/SignUpForm.tsx
- FE/src/utils/auth/fetchSignUp.ts
- 회원가입 시 유저네임 변수명 수정
- username -> userName으로 수정
> 회원가입 시 유저네임 변수명 수정

- FE/src/Components/KHJ/Nav/NavTop.tsx
> 관리자 계정 확인 로직 수정

- FE/src/Components/CYW/Search/SearchList.tsx
> [refactor] 간결하게 코드 수정

- FE/src/Components/KYH/admin/ProductList/OrderListBtnContainer.tsx
- FE/src/Components/LSM/Main/BestProduct/BestItem.tsx
- FE/src/Components/LSM/Main/BestReview/ReviewItem.tsx
- FE/src/Components/LSM/Main/BestReview/ReviewItemList.tsx
- FE/src/Components/LSM/Main/NewProduct/NewItem.tsx
- FE/src/Components/LSM/Main/ThemeProduct/ThemeItemList.tsx
- 수정하기 버튼 라우터 수정
- 상품 목록 네비게이터 수정
> 관리자 페이지 상품 리스트 내 수정 버튼, 메인 랜딩 페이지 네비게이터 수정

- FE/src/Components/LSM/Main/ThemeProduct/ThemeItem.tsx
- FE/src/Components/LSM/Main/ThemeProduct/ThemeItemList.tsx
> 메인 랜딩 페이지 네비게이터 수정

- FE/src/Components/LSM/Main/ThemeProduct/ThemeItem.tsx
> 메인 랜딩페이지 네비게이터 수정

- FE/src/Pages/LSM/Product/ProductEdit.tsx
> 상품 수정 페이지 수정

- FE/src/Components/CYW/ProductDetail/ProductInformation/Button.tsx
- FE/src/Components/CYW/ProductDetail/ProductInformation/OptionChoice.tsx
- FE/src/Components/CYW/ProductDetail/ProductInformation/ProductInformation.tsx
- FE/src/Components/CYW/ProductDetail/ProductInformation/SelectedResult.tsx
- FE/src/Components/CYW/Search/SearchList.tsx
- FE/src/Components/KHJ/Purchase/DeliverForm.tsx
- FE/src/Components/KYH/admin/ProductInquiry/InquiryAnswerContainer.tsx
- FE/src/Components/LSM/Product/ProductForm/ImageInput.tsx
- FE/src/Components/LSM/Product/ProductForm/OptionInput.tsx
- FE/src/Components/LSM/Product/ProductForm/ProductForm.tsx
- FE/src/utils/productDetail/fetchReview.ts
- 제품상세페이지 옵션 선택 시 제품선택결과 반영 등 디자인 및 기능 추가
- 기타 콘솔로그 제거
> 제품상세페이지 옵션관련 디자인 및 기능 추가

- FE/src/Components/CYW/ProductDetail/Tab/InquiryTab/InquiryElement.tsx
- FE/src/Components/CYW/ProductDetail/Tab/InquiryTab/InquiryRegister.tsx
- FE/src/Components/KYH/admin/ProductInquiry/ProductInquiry.tsx
- FE/src/Components/KYH/admin/ProductInquiry/SearchTableContents.tsx
- FE/src/hooks/admin/inquiry/useFetchInquiryPaging.ts
- 관리자 상품문의 페이지 필터링 로직 변경
- 기존 : 답변대기중, 답변완료 택 1
- 변경 : 모두 선택 및 모두 해제 가능
> 관리자 상품문의페이지 필터링 로직 변경

- BE/backend/src/main/java/project/main/webstore/domain/cart/controller/CartController.java
- BE/backend/src/main/java/project/main/webstore/domain/cart/dto/CartGetResponseDto.java
- BE/backend/src/main/java/project/main/webstore/domain/cart/dto/LocalCartDto.java
- BE/backend/src/main/java/project/main/webstore/domain/cart/dto/OptionDto.java
- BE/backend/src/main/java/project/main/webstore/domain/cart/entity/Cart.java
- BE/backend/src/main/java/project/main/webstore/domain/cart/entity/CartItem.java
- BE/backend/src/main/java/project/main/webstore/domain/cart/mapper/CartMapper.java
- BE/backend/src/main/java/project/main/webstore/domain/cart/repository/CartRepository.java
- BE/backend/src/main/java/project/main/webstore/domain/cart/service/CartService.java
- BE/backend/src/main/java/project/main/webstore/domain/image/mapper/ImageMapper.java
- BE/backend/src/test/java/project/main/webstore/domain/cart/controller/CartControllerTest.java
- BE/backend/src/test/java/project/main/webstore/domain/cart/service/CartServiceTest.java
- BE/backend/src/test/java/project/main/webstore/domain/cart/stub/CartStub.java
- BE/backend/src/test/java/project/main/webstore/domain/item/stub/ItemStub.java
- BE/backend/src/test/java/project/main/webstore/domain/users/stub/UserStub.java
- BE/backend/src/test/java/project/main/webstore/totalTest/CartControllerTest.java
- BE/backend/src/test/resources/data/data.sql
1. CartMapper 로직 수정
- 변경 과정 Mapper에 일임
- 생성자의 중복 제거
2. Test 코드 구현 완료
> Cart 리펙토링 및 테스트 구현 완료

- BE/backend/src/main/java/project/main/webstore/domain/image/mapper/ImageMapper.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/controller/NoticeController.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/dto/NoticeGetSimpleResponseDto.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/entity/Notice.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/mapper/NoticeMapper.java
- BE/backend/src/main/java/project/main/webstore/domain/notice/service/NoticeGetService.java
- BE/backend/src/main/java/project/main/webstore/domain/review/controller/ReviewController.java
- BE/backend/src/main/java/project/main/webstore/domain/review/dto/ReviewGetResponseDto.java
- BE/backend/src/main/java/project/main/webstore/domain/review/entity/Review.java
- BE/backend/src/main/java/project/main/webstore/domain/review/mapper/ReviewMapper.java
- BE/backend/src/test/java/project/main/webstore/domain/notice/controller/NoticeControllerTest.java
- BE/backend/src/test/java/project/main/webstore/domain/notice/service/NoticeGetServiceTest.java
- BE/backend/src/test/java/project/main/webstore/domain/notice/service/NoticeServiceTest.java
- BE/backend/src/test/java/project/main/webstore/domain/notice/stub/NoticeStub.java
- BE/backend/src/test/java/project/main/webstore/stub/ImageStub.java
- BE/backend/src/test/java/project/main/webstore/totalTest/NoticeControllerTest.java
- BE/backend/src/test/java/project/main/webstore/totalTest/ReviewControllerTest.java
- BE/backend/src/test/resources/data/data.sql
- BE/backend/src/test/resources/data/schema.sql
> review Notice 테스트 구현 완료

- BE/backend/src/main/java/project/main/webstore/utils/FileUploader.java
- 이미지 처리 기능 활성
- 알고리즘 변경 md5 -> sha256 md5 deprecated
- System.out.print -> log 변경
- 변수명 변경
> 이미지 S3 저장 기능 구현 및 미사용 메서드 제거
